### ISSUE TITLE
Slate clay ore appears inconsistent with dirt

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#12]
![2019-06-29_00 08 18](https://user-images.githubusercontent.com/52297970/60375667-3d442900-9a02-11e9-9336-82715c01312f.png)
To the left is slate dirt, to the right is slate clay.

**Comment by Bunsan** [comment]
There is an issue in the dirt texture. That is the placeholder texture for the slate pathblock top being applied to all sides. The texture is correct in pathblock side. The correct texture can be copied from there.
