### ISSUE TITLE
Filling jugs uses bucket filling sound event, leading to illogical subtitles

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#128]
In case it isn't obvious, jugs aren't buckets.
![2019-12-31_01 13 36](https://user-images.githubusercontent.com/52297970/71606688-21653f80-2b6b-11ea-9694-08f2a6af1b71.png)

**Comment by alcatrazEscapee** [comment]
It's the same sound that's being played, thus, has the same subtitle.
