### ISSUE TITLE
Small surface ores of native metals should be called nuggets

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#13]
They're called nuggets in 1.7.10, but not 1.12.2.

![2019-06-29_18 04 56](https://user-images.githubusercontent.com/52297970/60387296-d6be1a00-9a98-11e9-9bde-b32e31ef32e4.png)

![2019-06-29_18 02 00](https://user-images.githubusercontent.com/52297970/60387301-dfaeeb80-9a98-11e9-939f-1867e3c37f85.png)

**Comment by alcatrazEscapee** [comment]
Fixed in #26
