### ISSUE TITLE
部分汉化内容存在明显问题

### ISSUE THREAD

**Issue by 3d-pinball** [TerraFirmaCraft/TFC-Assets#130]
部分汉化内容存在明显问题
如 loot entries 应为“战利品表”而非“掠夺表”
“Leaf Stick Drop Chance Tool Classes”应为“使用对应工具破坏树叶时掉落木棍的几率”而非“工具类树叶掉落木棍几率”
Pit kiln 应为“陶瓷窑”而非“坑窑”
Torch 应为火把而非“火炬”
Modifier 应为“修正值”而非“修改”
Propagate 应为“蔓延”而非“传播”
Slashing 应为“劈砍”而非“砍击”
Piercing 应为“穿刺”而非“刺击”
Crushing 应为 “压砸”而非“锤击”
Nugget 应为“矿粒”而非“粒”
World Regeneration Debris Modifier 应为“地表资源刷新修正值”而非“地表物资重生修改”
Charcoal Pit 应为“木炭坑”而非“木炭炉”
Overlay 应为“蒙版”而非“覆盖层”
Bismuth_bronze 应为“铋青铜”而非“铋铜”
black_bronze 应为“黑青铜”而非“黑铜”
flat 应为“杂物”而非“平面”

**Comment by 3TUSK** [comment]
@HeartyYF 

---

"Overlay" is something like this https://www.w3schools.com/howto/howto_css_overlay.asp. “蒙版” doesn't sound belonging here.

**Comment by HeartyYF** [comment]
感谢您的反馈。
loot table 是我的问题，loot entries 应当是“战利品表项”，会修正的。
Leaf Stick Drop Chance Tool Classes 被讨论了好久了，我们希望在配置界面里它能起到能让人一眼就明白的作用，而不是塞一个很长的东西进去，很长的东西应当放在悬浮框里作为详细介绍。您可以看到，其下面的详细解释和您提出的修改意见相一致。我认为调整为“树叶工具类掉落木棍几率”或许会好一点。
Pit Kiln 并不是只能用来烧陶瓷，希望您告知为何应当叫做陶瓷窑。
Torch 翻译作“火炬”是希望与原版的火把作一个区分，因为群峦中的torch会自动熄灭。这一尝试似乎不够成功，我们会再度讨论这一问题。
Modifier 已经修正。
Propagate 应当是用于形容塌方的，我们认为用“蔓延”作为塌方的谓语不甚合适。或许使用“扩散”会更好一点？而且“塌方的方块使塌方蔓延的几率”听上去也很别扭。需要更多的讨论。
Slashing，Piercing，Crushing只是为了统一为“x击”这样的翻译。如若您认为这一统一没有必要或者有更好的方法，请务必告知。
Nugget 有两种，一类是作为ore的，另一类是作为metal的。后者翻译成粒和原版相一致应当没有问题，前者由于有Native（原生）这个前缀应当也不需要强调是“矿粒”。
World Regeneration Debris Modifier 和群峦的设定相一致，应当是“物资重新生成/再生成”而不是刷新。现在修改为“世界再生最小时间”和“地表资源再生修正值”了。
Charcoal Pit 已修改。
Overlay 这个应该不是蒙版，但准确翻译是什么我也不清楚，目前翻译成“覆盖层”，或许叫“叠加层”更好一点？
两种bronze我会去请教专业人士。根据我的了解，bronze泛指铜合金，而青铜的界定很模糊：有人认为特指含锡或者铅的合金，有人认为锌与镍之外的都是青铜，我们认为在这里直接叫“x铜”比较好。
**EDIT：** 请教了专业人士，现代的bismuth bronze是bismuth+brass（黄铜），这一点和群峦本身配方一致，她建议翻译作铋黄铜。她认为black bronze这一说法或许已经被弃用了，因为她没找到相关文献。
flat。。我没找到哪里有平面。。目前就是“杂物”没错啊。。难道Flat Bedrock应当是杂物基岩？

顺便，可能植物/树木/岩石部分需要更仔细地检查。有兴趣实时讨论而不是版聊的话，不妨加群：https://jq.qq.com/?_wv=1027&k=5qYiU65

**Comment by alcatrazEscapee** [comment]
If there's an actual translation issue, then it needs to get fixed in a PR. This is not really the place for discussion about translation as we can do nothing about it, it's entirely community driven.
