### ISSUE TITLE
Some crop textures are too high-res and look out of place

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#38]
![2019-07-20_12 14 04](https://user-images.githubusercontent.com/52297970/61583660-ea5a1f00-ab32-11e9-8d28-b87737aece65.png)
![2019-07-20_12 58 56](https://user-images.githubusercontent.com/52297970/61583662-f2b25a00-ab32-11e9-8d41-b0d0f3e8cf15.png)

**Comment by alcatrazEscapee** [comment]
They should either be remodeled to be two block tall crops, or just do what 1.7.10 did and stretch the textures larger.
