### ISSUE TITLE
Venison looks too high up

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#52]
![2019-08-04_22 12 12](https://user-images.githubusercontent.com/52297970/62429307-fdf5b000-b704-11e9-9fe2-2e457123ab3a.png)

It should be lowered by a pixel or two.

**Comment by alcatrazEscapee** [comment]
bc8e9c2f216c8ba9d3aaaa661ef34586a75e7c64
