### ISSUE TITLE
Hoe heads seem a bit too far down

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#55]
They should be moved up a bit to appear more centered.

![2019-08-04_23 27 32](https://user-images.githubusercontent.com/52297970/62430100-8711e480-b70f-11e9-8dd2-4efc48d6610c.png)

**Comment by alcatrazEscapee** [comment]
bc8e9c2f216c8ba9d3aaaa661ef34586a75e7c64
