### ISSUE TITLE
Unfired javelin head mold has the hollow bit off center, or so it appears

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#56]
![2019-08-04_23 28 51](https://user-images.githubusercontent.com/52297970/62430116-b32d6580-b70f-11e9-8207-ead5ed319ebb.png)

**Comment by alcatrazEscapee** [comment]
bc8e9c2f216c8ba9d3aaaa661ef34586a75e7c64
