### ISSUE TITLE
Stone javelin heads appear off-center

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TFC-Assets#57]
Moving them slightly to the right may fix this.

![2019-08-04_23 30 05](https://user-images.githubusercontent.com/52297970/62430130-dbb55f80-b70f-11e9-9a18-4b9e95824fd1.png)

**Comment by alcatrazEscapee** [comment]
bc8e9c2f216c8ba9d3aaaa661ef34586a75e7c64
