### ISSUE TITLE
Unsynchronized naming issue

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TFC-Assets#72]
![2019-08-08_22 09 37](https://user-images.githubusercontent.com/17660052/62711406-95bc0c80-ba2b-11e9-8c9e-bf197cd4761b.png)
![2019-08-08_22 09 41](https://user-images.githubusercontent.com/17660052/62711412-981e6680-ba2b-11e9-87f8-9c2bc2906e65.png)
![2019-08-08_22 09 45](https://user-images.githubusercontent.com/17660052/62711417-994f9380-ba2b-11e9-87b5-02260f2e567c.png)
You can see these should follow a same naming rule but they act differently. I think latter 2 shouldn't have space in their name.

**Comment by HeartyYF** [comment]
These are spliced name

**Comment by alcatrazEscapee** [comment]
As I said earlier:
> I can't see the issue, as I don't read Chinese. If you're going to report issues with screenshots, please take them in English.

**Comment by HeartyYF** [comment]
As I said it won't become an issue using English because in English there should be space but in Chinese there shouldn't

**Comment by HeartyYF** [comment]
I think the best way to solve it is to write "%s %s" to the language file....
If you don't think it as an issue, I will fix it myself.
