### ISSUE TITLE
Athyrium Fern clips into blocks

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TFC-Assets#86]
As per picture. The fern clips into the grass block to the left. Not sure if this is a solvable issue or if it is worth the effort.
![2019-07-13_11 31 33](https://user-images.githubusercontent.com/35673674/61173488-06bdf080-a562-11e9-8018-c85d78188a85.png)

**Comment by Azaysol** [comment]
could maybe lessen the clipping by making them closer togethere in the center and making them angle higher and shorten the length a bit
